name: Test

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    
    - name: Build and Run Tests
      run: |
        mvn clean compile
        
        mvn dependency:resolve
        
        mvn test -Dtest=StatusCodeApiUiTest -Dheadless=true
    
    - name: Upload test reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Test-Reports
        path: target/surefire-reports/
